### ISSUE TITLE
quest hickups

### ISSUE THREAD

**Issue by simonbuehler** [Map-A-Droid/MAD#67]
hi,

great work, just a list of hickups so far with quest scanning:

- [x] ~~check if pogo is in foreground before doing swipes /back / touchevents and don't do random stuff on the desktop~~
- [x] ~~after restarting mad because two workers send locations at the same time the route starts with first waypoint, ignoring needed waiting time - data time out, restart, loop~~
- [ ] quest rewards (spin stops) are not recognized when deleting quests, implement "accept" or "run away" logic
- [x] ~~don't go 🛒, think this happens when trying to clear bag but not shure~~
- [x] When cleaning bag: After "Click Gift / Raidpass" somehow the nearby pokemon gets clicked and hangs in the Pokestop image fullscreen display (trytodelete item-> "back"-> lower right click-> small swipe->click pokemon navigation -> pokestop details) ->reboot, loop
- [x] ~~Some stops are not reached, location is some meters off but would be reachable if  Orientation would be rotated a bit~~ not quest specific
- [x] ~~Save some time and clear quest while walking to stop~~

**Comment by cecpk** [comment]
Master?

**Comment by simonbuehler** [comment]
yup

**Comment by cecpk** [comment]
pls check new master again. thx

**Comment by cecpk** [comment]
status pls

**Comment by simonbuehler** [comment]
updated

**Comment by simonbuehler** [comment]
added new finding

**Comment by korentzari** [comment]
Not waiting next stop for remove previous quest.
Make cleaning quest when rgc walk

**Comment by cecpk** [comment]
fixed with branch mitmbase

**Comment by simonbuehler** [comment]
still hangs when trying to remove gifts (at first position), doesn't sucseed and gets into nearby
fhd resolution, mitmbase

**Comment by cecpk** [comment]
Pls contact me on discord! Thx

**Comment by cecpk** [comment]
fixed with new branch

**Comment by simonbuehler** [comment]
great work! somehow tessereact wasn't installed but after emerging it everything worked great!
closing

**Comment by simonbuehler** [comment]
pls merge to master
